# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  NotifyTeams:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: "https://capgemini.webhook.office.com/webhookb2/3f6bd7ab-2b20-4718-9447-65ac38d3c76c@76a2ae5a-9f00-4f6b-95ed-5d33d77c4d61/IncomingWebhook/953e697e7d38418686de7cce9836071d/409da6fc-5603-4c85-9211-6d21d3ee0686"
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          dry_run: False
