name: Python Workflow

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.6'  # Use the appropriate Python version

      - name: Run Python script
        run: python ../../pipeline.py --webhook_url ${{ secrets.MSTEAMS_WEBHOOK }} --pat_token ${{ secrets.PAT_TOKEN }} 
