name: Python Workflow

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: ls

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          pip install pyyaml
          pip install requests
          pip install PyGithub
          pip install tabulate

      - name: Run Python script
        env:
          WEBHOOK: ${{ secrets.MSTEAMS_WEBHOOK }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: python PipelineStatus.py --webhook_url "$WEBHOOK" --pat_token "$PAT_TOKEN"
